# This is a basic workflow to help you get started with Actions

name: Docker Image CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  push_to_registries:
    # The type of runner that the job will run on
      name: Push Docker Image to multiple registries
      runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Check out the repo
        - uses: actions/checkout@v2

      # Runs a single command using the runners shell
        - name: Build and Publish head Docker Image
          run: nachiketa91/repo1
          with:
            github-token: ${{ secrets.TOKEN }}
            image-name: myjavaapp
            image-tag: v1
        

 
